
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label1;

	private global::Gtk.Entry userID;

	private global::Gtk.Label label11;

	private global::Gtk.Label label10;

	private global::Gtk.ComboBox patternChoice;

	private global::Gtk.Button testButton;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button startButton;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.Label label8;

	private global::Gtk.Label timer;

	private global::Gtk.Label label12;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label14;

	private global::Gtk.DrawingArea drawingarea9;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Image image3;

	private global::Gtk.Image image7;

	private global::Gtk.Image image6;

	private global::Gtk.Image image4;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label13;

	private global::Gtk.DrawingArea drawingarea7;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Label label6;

	private global::Gtk.ComboBox patternFelt;

	private global::Gtk.Label counter;

	private global::Gtk.Label label9;

	private global::Gtk.HBox hbox4;

	private global::Gtk.DrawingArea drawingarea15;

	private global::Gtk.DrawingArea drawingarea14;

	private global::Gtk.Button submitButton1;

	private global::Gtk.HBox hbox18;

	private global::Gtk.Label label7;

	private global::Gtk.HScale patternRange;

	private global::Gtk.DrawingArea drawingarea11;

	private global::Gtk.Label label15;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Image image9;

	private global::Gtk.DrawingArea drawingarea13;

	private global::Gtk.Label label17;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label16;

	private global::Gtk.HScale patternRange1;

	private global::Gtk.DrawingArea drawingarea2;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Image image10;

	private global::Gtk.DrawingArea drawingarea3;

	private global::Gtk.DrawingArea drawingarea5;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("User ID:");
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(19));
		// Container child hbox3.Gtk.Box+BoxChild
		this.userID = new global::Gtk.Entry();
		this.userID.CanFocus = true;
		this.userID.Name = "userID";
		this.userID.IsEditable = true;
		this.userID.WidthChars = 9;
		this.userID.MaxLength = 9;
		this.userID.InvisibleChar = '●';
		this.userID.Xalign = 3.469447E-18F;
		this.hbox3.Add(this.userID);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.userID]));
		w2.Position = 1;
		w2.Padding = ((uint)(5));
		// Container child hbox3.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.hbox3.Add(this.label11);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label11]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(81));
		// Container child hbox3.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern Test:");
		this.hbox3.Add(this.label10);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label10]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.patternChoice = global::Gtk.ComboBox.NewText();
		this.patternChoice.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 1"));
		this.patternChoice.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 2"));
		this.patternChoice.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 3"));
		this.patternChoice.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 4"));
		this.patternChoice.Name = "patternChoice";
		this.patternChoice.Active = 0;
		this.hbox3.Add(this.patternChoice);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.patternChoice]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.testButton = new global::Gtk.Button();
		this.testButton.CanFocus = true;
		this.testButton.Name = "testButton";
		this.testButton.UseUnderline = true;
		this.testButton.BorderWidth = ((uint)(3));
		this.testButton.Label = global::Mono.Unix.Catalog.GetString("Test");
		this.hbox3.Add(this.testButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.testButton]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(9));
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.startButton = new global::Gtk.Button();
		this.startButton.CanFocus = true;
		this.startButton.Name = "startButton";
		this.startButton.UseUnderline = true;
		this.startButton.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox6.Add(this.startButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.startButton]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(17));
		// Container child hbox6.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea();
		this.drawingarea1.Name = "drawingarea1";
		this.hbox6.Add(this.drawingarea1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.drawingarea1]));
		w9.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Timer:");
		this.hbox6.Add(this.label8);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label8]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.timer = new global::Gtk.Label();
		this.timer.Name = "timer";
		this.timer.UseMarkup = true;
		this.timer.UseUnderline = true;
		this.timer.Wrap = true;
		this.hbox6.Add(this.timer);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.timer]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		w11.Padding = ((uint)(1));
		// Container child hbox6.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.hbox6.Add(this.label12);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label12]));
		w12.Position = 4;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(21));
		this.vbox1.Add(this.hbox6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.hbox2.Add(this.label14);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label14]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.drawingarea9 = new global::Gtk.DrawingArea();
		this.drawingarea9.Name = "drawingarea9";
		this.hbox2.Add(this.drawingarea9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.drawingarea9]));
		w15.Position = 1;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.image3 = new global::Gtk.Image();
		this.image3.Name = "image3";
		this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.pattern1.jpg");
		this.hbox8.Add(this.image3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.image3]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		w17.Padding = ((uint)(25));
		// Container child hbox8.Gtk.Box+BoxChild
		this.image7 = new global::Gtk.Image();
		this.image7.Name = "image7";
		this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.pattern2.jpg");
		this.hbox8.Add(this.image7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.image7]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(25));
		// Container child hbox8.Gtk.Box+BoxChild
		this.image6 = new global::Gtk.Image();
		this.image6.Name = "image6";
		this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.pattern3.jpg");
		this.hbox8.Add(this.image6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.image6]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		w19.Padding = ((uint)(25));
		// Container child hbox8.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image();
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.pattern4.jpg");
		this.hbox8.Add(this.image4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.image4]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(12));
		this.vbox1.Add(this.hbox8);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern 1");
		this.hbox10.Add(this.label2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label2]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		w22.Padding = ((uint)(79));
		// Container child hbox10.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern 2");
		this.hbox10.Add(this.label3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label3]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		w23.Padding = ((uint)(50));
		// Container child hbox10.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern 3");
		this.hbox10.Add(this.label4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label4]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		w24.Padding = ((uint)(93));
		// Container child hbox10.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern 4");
		this.hbox10.Add(this.label5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label5]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		w25.Padding = ((uint)(41));
		this.vbox1.Add(this.hbox10);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox10]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.hbox1.Add(this.label13);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label13]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea7 = new global::Gtk.DrawingArea();
		this.drawingarea7.Name = "drawingarea7";
		this.hbox1.Add(this.drawingarea7);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea7]));
		w28.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w29.Position = 5;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Pattern Felt:");
		this.hbox16.Add(this.label6);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label6]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		w30.Padding = ((uint)(16));
		// Container child hbox16.Gtk.Box+BoxChild
		this.patternFelt = global::Gtk.ComboBox.NewText();
		this.patternFelt.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 1"));
		this.patternFelt.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 2"));
		this.patternFelt.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 3"));
		this.patternFelt.AppendText(global::Mono.Unix.Catalog.GetString("Pattern 4"));
		this.patternFelt.Name = "patternFelt";
		this.patternFelt.Active = 0;
		this.hbox16.Add(this.patternFelt);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.patternFelt]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.counter = new global::Gtk.Label();
		this.counter.Name = "counter";
		this.counter.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.hbox16.Add(this.counter);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.counter]));
		w32.PackType = ((global::Gtk.PackType)(1));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		w32.Padding = ((uint)(14));
		// Container child hbox16.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Counter:");
		this.hbox16.Add(this.label9);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label9]));
		w33.PackType = ((global::Gtk.PackType)(1));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox1.Add(this.hbox16);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox16]));
		w34.Position = 6;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.drawingarea15 = new global::Gtk.DrawingArea();
		this.drawingarea15.Name = "drawingarea15";
		this.hbox4.Add(this.drawingarea15);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea15]));
		w35.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.drawingarea14 = new global::Gtk.DrawingArea();
		this.drawingarea14.Name = "drawingarea14";
		this.hbox4.Add(this.drawingarea14);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea14]));
		w36.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.submitButton1 = new global::Gtk.Button();
		this.submitButton1.CanFocus = true;
		this.submitButton1.Name = "submitButton1";
		this.submitButton1.UseUnderline = true;
		this.submitButton1.Label = global::Mono.Unix.Catalog.GetString("Submit");
		this.hbox4.Add(this.submitButton1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.submitButton1]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		w37.Padding = ((uint)(16));
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w38.Position = 7;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Index Finger Range:");
		this.hbox18.Add(this.label7);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.label7]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		w39.Padding = ((uint)(16));
		// Container child hbox18.Gtk.Box+BoxChild
		this.patternRange = new global::Gtk.HScale(null);
		this.patternRange.CanFocus = true;
		this.patternRange.Name = "patternRange";
		this.patternRange.Adjustment.Upper = 100D;
		this.patternRange.Adjustment.PageIncrement = 10D;
		this.patternRange.Adjustment.StepIncrement = 1D;
		this.patternRange.Adjustment.Value = 50.2024291497976D;
		this.patternRange.DrawValue = false;
		this.patternRange.Digits = 0;
		this.patternRange.ValuePos = ((global::Gtk.PositionType)(3));
		this.hbox18.Add(this.patternRange);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.patternRange]));
		w40.Position = 1;
		// Container child hbox18.Gtk.Box+BoxChild
		this.drawingarea11 = new global::Gtk.DrawingArea();
		this.drawingarea11.Name = "drawingarea11";
		this.hbox18.Add(this.drawingarea11);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.drawingarea11]));
		w41.Position = 2;
		w41.Padding = ((uint)(26));
		// Container child hbox18.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.hbox18.Add(this.label15);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.label15]));
		w42.Position = 3;
		w42.Expand = false;
		w42.Fill = false;
		w42.Padding = ((uint)(35));
		this.vbox1.Add(this.hbox18);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox18]));
		w43.Position = 8;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.image9 = new global::Gtk.Image();
		this.image9.Name = "image9";
		this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.FingerRange.jpg");
		this.hbox20.Add(this.image9);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.image9]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		w44.Padding = ((uint)(143));
		// Container child hbox20.Gtk.Box+BoxChild
		this.drawingarea13 = new global::Gtk.DrawingArea();
		this.drawingarea13.Name = "drawingarea13";
		this.hbox20.Add(this.drawingarea13);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.drawingarea13]));
		w45.Position = 1;
		this.vbox1.Add(this.hbox20);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox20]));
		w46.Position = 9;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.vbox1.Add(this.label17);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label17]));
		w47.Position = 10;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Middle Finger Range:");
		this.hbox5.Add(this.label16);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label16]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		w48.Padding = ((uint)(13));
		// Container child hbox5.Gtk.Box+BoxChild
		this.patternRange1 = new global::Gtk.HScale(null);
		this.patternRange1.CanFocus = true;
		this.patternRange1.Name = "patternRange1";
		this.patternRange1.Adjustment.Upper = 100D;
		this.patternRange1.Adjustment.PageIncrement = 10D;
		this.patternRange1.Adjustment.StepIncrement = 1D;
		this.patternRange1.Adjustment.Value = 50D;
		this.patternRange1.DrawValue = false;
		this.patternRange1.Digits = 0;
		this.patternRange1.ValuePos = ((global::Gtk.PositionType)(3));
		this.hbox5.Add(this.patternRange1);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.patternRange1]));
		w49.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.drawingarea2 = new global::Gtk.DrawingArea();
		this.drawingarea2.Name = "drawingarea2";
		this.hbox5.Add(this.drawingarea2);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.drawingarea2]));
		w50.Position = 2;
		w50.Padding = ((uint)(58));
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w51.Position = 11;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.image10 = new global::Gtk.Image();
		this.image10.Name = "image10";
		this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("UserStudyGUI.FingerRange.jpg");
		this.hbox7.Add(this.image10);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.image10]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		w52.Padding = ((uint)(148));
		// Container child hbox7.Gtk.Box+BoxChild
		this.drawingarea3 = new global::Gtk.DrawingArea();
		this.drawingarea3.Name = "drawingarea3";
		this.hbox7.Add(this.drawingarea3);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.drawingarea3]));
		w53.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.drawingarea5 = new global::Gtk.DrawingArea();
		this.drawingarea5.Name = "drawingarea5";
		this.hbox7.Add(this.drawingarea5);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.drawingarea5]));
		w54.Position = 2;
		this.vbox1.Add(this.hbox7);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
		w55.Position = 12;
		w55.Expand = false;
		w55.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 799;
		this.DefaultHeight = 706;
		this.Show();
		this.patternChoice.Changed += new global::System.EventHandler(this.ChangePatternTest);
		this.testButton.Clicked += new global::System.EventHandler(this.testButtonClicked);
		this.startButton.Clicked += new global::System.EventHandler(this.startButtonClicked);
		this.patternFelt.Changed += new global::System.EventHandler(this.ChangePatternFelt);
		this.submitButton1.Clicked += new global::System.EventHandler(this.SubmitButtonClicked);
		this.patternRange.ValueChanged += new global::System.EventHandler(this.ChangeIndexRange);
		this.patternRange1.ValueChanged += new global::System.EventHandler(this.ChangeMiddleRange);
	}
}
